-- Fleet assignment + finance columns, for the deploy of commit 3ac8695.
--
-- Production was deployed without this, so /invoices, /fleets and /finance
-- return 500 with P2021 (table "Fleet" missing) and P2022 (column missing).
--
-- Generated by `prisma migrate diff` between the previously deployed schema
-- (9a86b37) and the current one. Every statement is additive: no DROP, no
-- data rewritten. Existing rows get fleetId = NULL and paidAmount = 0.
--
-- DO NOT use `prisma db push` for this. Production still carries an unused
-- DailyPrice table left over from an older schema; db push would insist on
-- --accept-data-loss to drop it, and that flag has no business near the live
-- invoice tables. This script leaves DailyPrice untouched.
--
-- Rehearsed on 2026-09-14 against a local replica of production (same five
-- tables, same drift): all statements applied cleanly, DailyPrice and every
-- existing invoice row survived, and /invoices, /fleets and /finance served
-- 200 afterwards.

-- AlterTable
ALTER TABLE "Invoice" ADD COLUMN     "fleetId" TEXT,
ADD COLUMN     "paidAmount" DECIMAL(14,2) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "InvoiceItem" ALTER COLUMN "quantity" SET DEFAULT 0,
ALTER COLUMN "unitPrice" SET DEFAULT 0,
ALTER COLUMN "lineTotal" SET DEFAULT 0;

-- CreateTable
CREATE TABLE "Fleet" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "active" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Fleet_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Fleet_name_key" ON "Fleet"("name");

-- CreateIndex
CREATE INDEX "Invoice_fleetId_day_idx" ON "Invoice"("fleetId", "day");

-- AddForeignKey
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_fleetId_fkey" FOREIGN KEY ("fleetId") REFERENCES "Fleet"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

